-- AlterTable
ALTER TABLE `Document` MODIFY `level` ENUM('CITIZEN', 'CITY_ADMIN', 'DISTRICT_ADMIN', 'SUBDISTRICT_ADMIN', 'SUPERADMIN') NOT NULL;

-- AlterTable
ALTER TABLE `User` MODIFY `role` ENUM('CITIZEN', 'CITY_ADMIN', 'DISTRICT_ADMIN', 'SUBDISTRICT_ADMIN', 'SUPERADMIN') NOT NULL;
